"""
Conversation domain model.

Represents a bounded chat session owned by a User. A conversation
groups messages into a coherent context window for LLM processing
and provides the boundary for RAG retrieval in future phases.

Phase 2.3: Persistence model only — no session management or LLM logic.
"""

from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


def _utcnow() -> datetime:
    """Return the current UTC datetime (timezone-aware)."""
    return datetime.now(timezone.utc)


class Conversation(Base):
    """
    Persistent domain model for an ECHO-AI chat session.

    Columns
    -------
    id          : Integer surrogate primary key.
    user_id     : Non-null FK to users.id — every conversation must have an owner.
    title       : Nullable short description; intended to be generated by LLM
                  in a future phase once chat history exists.
    created_at  : UTC timestamp set automatically at insert time.
    updated_at  : UTC timestamp updated automatically on every modification.

    Relationships
    -------------
    user     : Many-to-one back to User.
    messages : One-to-many; all Message records within this conversation.
    """

    __tablename__ = "conversations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
    )

    # Relationships
    user: Mapped["User"] = relationship(
        "User",
        back_populates="conversations",
    )
    messages: Mapped[list["Message"]] = relationship(
        "Message",
        back_populates="conversation",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Conversation id={self.id} user_id={self.user_id} title={self.title!r}>"
