"""
Message domain model.

The fundamental transactional unit of ECHO-AI. Each record is an
immutable utterance from either the human user or the AI assistant
within a specific Conversation.

Role is constrained to a controlled set of values via a CHECK constraint
on the database column, mapped through Python's enum.Enum for type safety
at the application layer. VARCHAR + CHECK is used instead of a PostgreSQL
native ENUM type because native ENUM types are difficult to alter after
deployment (e.g., adding/removing values requires DDL changes with locks).

Phase 2.3: Persistence model only — no LLM processing or RAG logic.
"""

import enum
from datetime import datetime, timezone

from sqlalchemy import CheckConstraint, DateTime, ForeignKey, Integer, Text, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base


class MessageRole(str, enum.Enum):
    """Valid role values for a Message.

    - USER      : Input from the human.
    - ASSISTANT : Response generated by the AI system.
    - SYSTEM    : Internal system-level instruction or context injection.
    """

    USER = "user"
    ASSISTANT = "assistant"
    SYSTEM = "system"


def _utcnow() -> datetime:
    """Return the current UTC datetime (timezone-aware)."""
    return datetime.now(timezone.utc)


class Message(Base):
    """
    Persistent domain model for a single message within a Conversation.

    Columns
    -------
    id              : Integer surrogate primary key.
    conversation_id : Non-null FK to conversations.id.
    role            : VARCHAR(50) constrained to 'user', 'assistant', 'system'.
    content         : Non-null TEXT body of the message utterance.
    created_at      : UTC timestamp set automatically at insert time.
                      Messages are append-only; updated_at is intentionally absent
                      because modifying a message would break LLM context determinism.

    Relationships
    -------------
    conversation : Many-to-one back to Conversation.
    """

    __tablename__ = "messages"

    __table_args__ = (
        CheckConstraint(
            "role IN ('user', 'assistant', 'system')",
            name="ck_messages_role_valid",
        ),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    conversation_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("conversations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    role: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )
    content: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        index=True,
    )

    # Relationships
    conversation: Mapped["Conversation"] = relationship(
        "Conversation",
        back_populates="messages",
    )

    def __repr__(self) -> str:
        return f"<Message id={self.id} role={self.role!r} conversation_id={self.conversation_id}>"
